Start
CptPerebey/QA22_Vereshako_PrestaShop_Diplom pull request #1
Opened 2023-02-16 12:01 UTC by CptPerebey

2023-02-16 20:33 UTC, voropa requested changes

2023-02-16 20:33 UTC, voropa commented on src/test/java/Pages/CreatAccountPage.java
> +        driver.findElement(DAY_OF_BIRTH_LOCATOR).click();
При использовании класса-обертки Select не нужно предварительно делать click() по элементу, чтобы выбрать значение из списка

2023-02-16 20:33 UTC, voropa commented on src/test/java/Pages/HeadPage.java
> +    /*public void  selectSortingOrderOption2 (WebElement optionName) {
Что за код закоментированный? Удалите его

2023-02-16 20:33 UTC, voropa commented on src/test/java/Tests/LoginTest.java
> +    public void LoginTest(){
названия методов в java с маленькой буквы

2023-02-16 20:33 UTC, voropa commented on src/test/java/Tests/BaseTest.java
> +        driver.get("http://prestashop.qatestlab.com.ua/ru/");
Смотрите аккуратно с "/ru" в адресе страницы. НА сайте есть выбор языка. если вы явно в url указываете /ru  - то он будет всегда на русском языке отображаться. 
Кстати, там есть баги с языками

2023-02-16 20:33 UTC, voropa commented on src/test/java/Tests/RegisterTest.java
> +        Thread.sleep(5000);
Почему тут Thread.sleep()? Замените на явные ожидания.
И удалите закоментированный код

2023-02-20 08:53 UTC, voropa requested changes

2023-02-20 08:53 UTC, voropa commented on src/test/java/Pages/HeadPage.java
> +    public void  selectSortingOrderOption2 (String optionName) {
Зачем в названии метода цифра 2?

2023-02-20 08:53 UTC, voropa commented on src/test/java/Pages/HeadPage.java
> +        if (optionName == "Popular") {
Сделайте enum для этих optionName и используйте его тут, чтобы не хардкодить стринговые названия

2023-02-20 08:53 UTC, voropa commented on src/test/java/Tests/loginTest.java
> +public class loginTest extends BaseTest{
Названия классов как раз таки с большой букв должно быть

2023-02-20 08:53 UTC, voropa commented on src/test/java/Tests/loginTest.java
>      public void LoginTest(){
А вот названия методов с маленькой

2023-02-24 19:42 UTC, voropa requested changes

2023-02-24 19:42 UTC, voropa commented on src/test/java/Modal/BaseModal.java
> +    private static final By FILTER_TOPS_BUTTON = By.id("layered_category_4");
Очень плохие локаторы с индексами, которые могут в любой момент поменяться. Переделайте

2023-02-24 19:42 UTC, voropa commented on src/test/java/Tests/CardTests.java
> +        actions
В тестовых методов не должно быть acrtions, driver и прочих технических штук. Оберните это все в метод внутри page класса и вызывайте его тут

2023-02-24 19:42 UTC, voropa commented on src/test/java/Tests/CardTests.java
> +        Thread.sleep(2000);
Замените на явное ожидание, если оно тут нужно

2023-02-24 19:42 UTC, voropa commented on src/test/java/Tests/CardTests.java
> +        Thread.sleep(2000);
Замените на явное ожидание, если оно тут нужно

2023-02-24 19:42 UTC, voropa commented on src/test/java/Tests/SortingTests.java
> +        Thread.sleep(2000);
Замените на явное ожидание, если оно тут нужно

2023-03-01 19:26 UTC, voropa requested changes

2023-03-01 19:26 UTC, voropa commented on src/test/java/Pages/MyAccountPage.java
> +    private final static By MY_WISHLIST_BUTTON = By.xpath("//*[text()='Мои списки покупок']");
Очень стремный локатор с русскм текстом. Что если сайт переклбчить на английский, то локатор не будет работать

2023-03-01 19:26 UTC, voropa commented on src/test/java/Pages/ProductDetailsPage.java
> +    public void addToCardMassageIsPresent(){
Если метод ждет чего-то, то и называться должен waitFor....

2023-03-01 19:26 UTC, voropa commented on src/test/java/Pages/WishListPage.java
> +    protected static final By MY_WISHLIST = By.xpath("//a[@href= 'javascript:;']/../following-sibling::td/a[@onclick]");
Очень плохой локатор //a[@href= 'javascript:;']/../following-sibling::td/a[@onclick], переделайте

2023-03-02 19:43 UTC, voropa requested changes

2023-03-02 19:43 UTC, voropa commented on src/test/java/Pages/HeadPage.java
> +        if (optionName == "Popular") {
Все еще актуальный коментарий

2023-03-05 08:09 UTC, voropa requested changes

2023-03-05 08:09 UTC, voropa commented on src/test/java/Enams/SelectOptionOnHeadPage.java
> +    Popular("Popular"),
Названия эдементов в enum доолжны быть написаны в UPPER_CASE, например, POPULAR

2023-03-05 18:21 UTC, voropa reviewed
1. Добавьте во все логи данные в тех, методах, где есть входные аргументы, например, если вы пишите лог: "ввожу имя пользователя", то он должен быт вот таким:
Stirng.format("ввожу имя польщователя: %s", userName).
2. И проверьте орфографию и пунктуацию в логах, там много ошибок

2023-03-05 18:21 UTC, voropa commented on src/test/java/Enams/State.java
> +package Enams;
названия пакетов в java дожны быть с маленькой буквы, а если название в несколько слов, то пишут их через-тире. пересмотрите все ваши пакеты

2023-03-05 18:21 UTC, voropa commented on src/test/java/Enams/State.java
> +package Enams;
И еще,  emuns, а не enAms)

2023-03-05 18:21 UTC, voropa commented on src/test/java/Modal/NewAddressModal.java
> +        log.info("Заполняю полять для создания адреса");
От такого лога нет большого смысла. Логи нудно писать вместе с актуальными данными, которые вводятся и т.д. 
В этом случае будет правильно добавить обьект address в строку с логированеим

2023-03-05 18:21 UTC, voropa commented on src/test/java/Modal/NewUserModal.java
> +        log.info("Заполняю полять для создания аккаунта");
То же самое с логом тут

2023-03-05 18:21 UTC, voropa commented on src/test/java/Tests/RegisterTest.java
> +    @Test(groups = {"SmokeTests"})
А в чем разница между этими двумя тестами в этом классе?

2023-03-05 18:21 UTC, voropa commented on src/test/java/Tests/SortingTests.java
> +    @Test(groups = {"SmokeTests"}, description = "Test to check the sorting of products on the main page",
Плохо, что у вас часть логов и description тестов на русском языке, а часть на английском. Выберите один я зык и перепишите все логи и descriptions на нем

2023-03-08 20:33 UTC, voropa requested changes

2023-03-08 20:33 UTC, voropa commented on Negative.xml
> +    <test name="All Smoke tests">
Почему тут в названии 'Smoke tests', а сам сьют negative?

2023-03-08 20:33 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    public void setUp(@Optional("Chrome") String browserName, @Optional("true") String headless, ITestContext testContext) throws Exception{
Через аннотации @Parameters и @Optional вы считываете параметры из testNg.xml файлов, но у вас там нет параметоров. А для того, чтобы считывать параметры из Jenkins CLI, точнее из команды mvn clan test -D...
Вам нужно использовть System.getProperty(). Разберитесь с этим

2023-03-08 20:33 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +            if (headless.equals("false"))    {
Странная логика, вдумайтесь что тут написано внутри if

2023-03-08 20:33 UTC, voropa commented on src/test/java/tests/TestLisener.java
> +    @Attachment(value = "screenshot", type = "image/png")
А зачем вам screenshot, когда тест проошел и он зеленый?

2023-03-08 20:33 UTC, voropa commented on src/test/java/tests/TestLisener.java
> +    @Attachment(value = "screenshot", type = "image/png")
И тут зачем вам аннотация эта, у вас же внутр метода onTestFailure вызывается AllureUtils.attachScreenshot(driver);

2023-03-08 20:33 UTC, voropa commented on src/test/java/Tests/SortingTests.java
> +    @Test(groups = {"SmokeTests"}, description = "Test to check the sorting of products on the main page",
Все еще актуально

2023-03-08 20:35 UTC, voropa commented on src/test/java/Modal/NewAddressModal.java
> +        log.info("Заполняю полять для создания адреса");
Доолжно быть как-то так:
log.info(String.format("Заполняю поля для создания адреса: %s", address))

2023-03-09 13:30 UTC, voropa requested changes

2023-03-09 13:30 UTC, voropa commented on Smoke.xml
> +        <parameter name="browser" value="Chrome"></parameter>
В таком случае нет смысла добавлять в suite.xml фалах тут parameter "browser ", он теперь не вычитывается тсюда а берется из mvn clena test -Dbrowser кооманды

2023-03-09 13:30 UTC, voropa commented on Smoke.xml
> +        <parameter name="browser" value="Chrome"></parameter>
ну и в параллель на 2х браузерах вы не сможете запустить таким образом. оптому что барузер всегда будщет одинаковый, тот, который вы уражете в -Dbrowser при запуске через  maven

2023-03-09 18:37 UTC, voropa requested changes

2023-03-09 18:37 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +            if (headless.equals("false"))    {
все еще актуально про if(headless)

2023-03-09 18:37 UTC, voropa commented on Regression.xml
> +    <parameter name="browser" value="chrome"></parameter>
Вижу, что все таки решили передавать параметр browser из командной строки при запуске через mvn. Тогда вам в .xml фалйах тут не нужен <parameter name="browser" value="chrome"></parameter>. Проверьте все suite  файлы и удалите там этот параметр

2023-03-10 07:45 UTC, voropa requested changes

2023-03-10 07:45 UTC, voropa commented on src/test/java/pages/AuthenticationPage.java
> +/*    @Step
Why commented?

2023-03-10 07:45 UTC, voropa commented on src/test/java/pages/AuthenticationPage.java
> +    public boolean waitToCreateButtonIsPresent() {
Так это же не  вэйт, метод же не ждет ничего, а делаает findElememnt и возвращает true/false. Поменяйте название мметода

2023-03-10 07:45 UTC, voropa commented on src/test/java/pages/CreatAccountPage.java
> +    public boolean waitCreateButtonIsPresent(){
Опять же таки, это не wait

2023-03-10 07:45 UTC, voropa commented on src/test/java/pages/HeadPage.java
> +    @Step
Это еще что за implicityWaitForTest?? 
implicityWait -парметр, который задается одиин раз, обычно при запуске браузера в before методе и потом selenium сам его использует. Аа вы этот метод тут добавили и хотите его вызывать потом где-то в тестах??

Вспоминайте теорию: https://docs.google.com/presentation/d/1nfqmUEuj7h-nyH6d0g8ZnPiBblN-CuelzkBCubuO8AY/edit#slide=id.g70ee74ebc3_0_212

2023-03-10 07:45 UTC, voropa commented on src/test/java/pages/HeadPage.java
> +    public boolean waitLoginButtonButtonIsPresent() {
И тут с названием метода беда

2023-03-10 19:35 UTC, voropa requested changes

2023-03-10 19:35 UTC, voropa commented on src/test/java/tests/CardTests.java
> +        Thread.sleep(2000);
Уберите thread.sleep(), замените их на явные ожидания

2023-03-10 19:38 UTC, voropa requested changes

2023-03-10 19:38 UTC, voropa commented on src/test/java/Tests/RegisterTest.java
> +        Assert.assertEquals(myAccountPage.getAccountMassage(),"Welcome to your account. Here you can manage all of your personal information and orders.");
Вынесите текст этого сообщеняи в константу какую-нибудь в baseTest нпример, он (текст) используется у ва с в нескольких тестах

2023-03-12 11:54 UTC, voropa requested changes

2023-03-12 11:54 UTC, voropa commented on src/test/java/tests/AddressTest.java
> +        Thread.sleep(2000);
Почему тут появился Thread.sleep()???

2023-03-12 11:54 UTC, voropa commented on src/test/java/tests/LoginTest.java
> +    @Test(groups = {"Regression"},description = "Тест на проверку авторизации")
Ну вообще обычно позитивный тест на логин - это смоук тест, потому что это критично важный функционал

2023-03-13 17:37 UTC, voropa requested changes

2023-03-13 17:37 UTC, voropa commented on src/test/java/tests/LoginTest.java
> +    public void loginTest(){
А чего тут у вас только один позитивный тест на логин? 
Добавьте хотя бы один еще негативный тест.

2023-03-13 21:06 UTC, CptPerebey commented on src/test/java/Tests/RegisterTest.java
> +    @Test(groups = {"SmokeTests"})
Первый регистрирует пользователя для LoginTest. Так как сайт тестовый данные о пользователях удаляются и я не могу зарегистрировать постоянный аккаунт

2023-03-13 21:28 UTC, voropa requested changes

2023-03-13 21:28 UTC, voropa commented on src/test/java/tests/TestLisener.java
> +        System.out.println("Test " + result.getName() + " started at" + new Date().toString());
Замените все system.out на log.info/debug()

2023-03-13 21:28 UTC, voropa commented on src/test/java/tests/LoginTest.java
> +    @Test(dataProvider = "negativeLoginTestData", groups = "Smoke", description = "Негативный тест на авторизацию")
И все же, почему у вас позитивный тест на логин - это regression, а негативный - это smoke?
Тут еще в негативном неправильно группа указана без {}, он так не будет запускаться

2023-03-13 21:28 UTC, voropa commented on src/test/java/Tests/RegisterTest.java
> +    @Test(groups = {"SmokeTests"})
Стоп, т.е. у вас этот тест должен выполняться, чтобы создался аккаунт и смогли выполниться остальные тесты??? Т.е. у вас все тесты зависят от этого??
Это в корне  неправильно.
Если вам нужно создавать аккаунт для тестов, то делать это нужно в pre-condition, в методах beforeSuite/beforeTest/beforeClass в BaseTest, а не в тестовом методе

2023-03-13 21:28 UTC, voropa commented on src/test/java/Tests/RegisterTest.java
> +    @Test(groups = {"SmokeTests"})
Да, и email/pass зачем хардкодить, оонии же есть у вас в config.properties

2023-03-13 21:58 UTC, CptPerebey commented on src/test/java/tests/LoginTest.java
> +    @Test(dataProvider = "negativeLoginTestData", groups = "Smoke", description = "Негативный тест на авторизацию")
У меня запускается и проходит 3 раза с разными данными

2023-03-14 09:59 UTC, voropa requested changes

2023-03-14 09:59 UTC, voropa commented on src/test/java/pages/CreatAccountPage.java
> +    public String getNameRandom(){
Что это за методы со странным названием и зачем? Они же нигде не используются, насколько я вижу

2023-03-14 09:59 UTC, voropa commented on src/test/java/tests/LoginTest.java
> +    public void loginTestWithRandomData() {
новый тест вы добавили, а старые зависимые тесты почему не удалили?

2023-03-14 09:59 UTC, voropa commented on src/test/java/tests/LoginTest.java
> +        headPage.loginButtonIsPresent();
Какой смысл от этой строчки кода тут?    
headPage.loginButtonIsPresent(); - она же возвращает boolean значение, которое вы нигде не используете

2023-03-14 09:59 UTC, voropa commented on src/test/java/tests/LoginTest.java
> +        authenticationPage.setEmailForRegister(email);
Создание пользователя должно быть в pre-condition, а вот уже сам процесс логина - в тесте

2023-03-14 12:39 UTC, voropa requested changes

2023-03-14 12:39 UTC, voropa commented on src/test/java/tests/BaseTest.java
> -    public final static String BASE_PASSWORD = PropertyReader.getProperty("password");
Теперь вам вероятно не нужны password и userEmail в config.properties файле, так как они не используются, удалите их оттуда

2023-03-14 12:47 UTC, CptPerebey commented on src/test/java/pages/CreatAccountPage.java
> +    public String getNameRandom(){
Это я придумывал как забрать данные во время регистрации и пробросить в логин. Удалил

2023-03-14 12:49 UTC, voropa requested changes

2023-03-14 12:49 UTC, voropa commented on src/test/java/modal/NewUserModal.java
> +    public static void fillFormUser(User user) {
Почему этот метод тут static? У вас же создается экземпляр этого класса, передается туда драйвер, чтобы работать с ним, так что метод не должен быть static

2023-03-14 12:49 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +        NewUserModal.fillFormUser(testUser);
Соотвественно тут вы не должны обращаться к NewUserModal классу и его статичному методу fillFormUser, а должны использовать конкретный экземпляр newUserModal, который инициализируется выше в beforeClass

2023-03-14 12:49 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    public final static String BASE_USERNAME = PropertyReader.getProperty("userName");
Вот эти 2 константы нигде не используются, соотвественн оудалите их отсюда и из config.properties
<img width="862" alt="image" src="https://user-images.githubusercontent.com/14195681/225005001-662d9b7e-2e0c-41d9-bc1f-387f9c12a120.png">

2023-03-14 12:49 UTC, voropa commented on src/test/java/pages/CreatAccountPage.java
> +public class CreatAccountPage extends BasePage{
В этом классе очень много неиспользуемых методов и переменных, удалите их (выделены серым).
И еще опечатка в названии самого класса, исправьте
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/14195681/225005445-ebb343db-e51d-4109-b6fc-3415ceb28f9f.png">

2023-03-14 12:49 UTC, voropa commented on src/test/java/pages/ProductDetailsPage.java
> +    public void waitAddToCardButtonIsPresent(){
Вот этот метод тоже нигде не используется, так что удалите его. И пройдитесь вообще  по  всем классам, почистите код, удалите неиспользуемые методы, переменные, импорты. Их IDEA выделяет серым цветом

2023-03-14 13:38 UTC, voropa approved these changes

2023-03-14 13:40 UTC, merged

2023-03-14 13:41 UTC, voropa commented on src/test/java/pages/ProductDetailsPage.java
> +    public void waitAddToCardButtonIsPresent(){
**И пройдитесь вообще по всем классам, почистите код, удалите неиспользуемые методы, переменные, импорты. Их IDEA выделяет серым цветом.**
У вас все еще есть неиспользуемые методы в разных классах!